name: Deploy to EC2
on:
    push:
        branches:
            - main

    
          
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
         - name: Cheking out code on runner
           uses: actions/checkout@4

         - name: Login and update the EC2 instances
           uses: appleboy/ssh-action@v1.0.3
           with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USERNAME }}
             password: ${{ secrets.EC2_SSH_KEY }}
             port: 22
             script: |
              pwd
              whoami
              sudo apt-get update -y
              
          
            
             

